### ISSUE TITLE
problem on ubuntu 18.04

### ISSUE THREAD

**Issue by mrheat** [raszia/save_network_configuration#3]
python3 save_my_network.py --exclude-connected-routes --disable-dhcp-interfaces --network my_network.sh --iptables my_iptables.sh --resolv my_resolv.sh
iptables configuration saved to my_iptables.sh
Traceback (most recent call last):
  File "save_my_network.py", line 202, in <module>
    save_network_config_to_file(args.network)
  File "save_my_network.py", line 111, in save_network_config_to_file
    append_interface_flags(commands, interface)
  File "save_my_network.py", line 61, in append_interface_flags
    with open(f"/sys/class/net/{interface}/flags", "r") as flags_file:
NotADirectoryError: [Errno 20] Not a directory: '/sys/class/net/bonding_masters/flags'

**Comment by mrheat** [comment]
System is configured with 2 links lacp bond to the same switch
 ProLiant DL360 Gen9
HPE Ethernet 1Gb 4-port 331i Adapter - NIC

**Comment by mrheat** [comment]
# The loopback network interface
auto lo
iface lo inet loopback

auto eno1
iface eno1 inet manual
  bond-master bond0

auto eno2
iface eno2 inet manual
  bond-master bond0

auto bond0
iface bond0 inet manual
  hwaddress 7a:41:93:34:f0:54
  bond-slaves eno1 eno2
  bond-mode 4
  bond-miimon 100

auto bond0.115
iface bond0.115 inet static
  address XX.XX.XX.XX
  netmask 255.255.255.0
  gateway XX.XX.XX.XX
